var exemptions = [
  {
    name: "Section 12",
    reason: "on grounds of cost.",
    reference: "https://www.foiman.com/archives/802",
    searchStrings: [
        "section 12",
        "s.12",
        "s 12",
        "s12",
      ],
  },
  {
    name: "Section 14",
    reason: "as they deemed it vexatious.",
    reference: "https://www.foiman.com/archives/767",
    searchStrings: [
        "section 14",
        "s.14",
        "s 14",
        "s14",
      ],
  },
  {
    name: "Section 21",
    reason: "as the information is reasonably available by other means.",
    reference: "https://www.foiman.com/archives/782",
    searchStrings: [
        "section 21",
        "s.21",
        "s 21",
        "s21",
      ],
  },
  {
    name: "Section 22a",
    reason: "...",
    reference: "https://www.foiman.com/archives/1119",
    searchStrings: [
        "section 22a",
        "s.22a",
        "s 22a",
        "s22a",
      ],
  },
  {
    name: "Section 22",
    reason: "as the information is intended for future publication.",
    reference: "https://www.foiman.com/archives/1105",
    searchStrings: [
        "section 22",
        "s.22",
        "s 22",
        "s22",
      ],
  },
  {
    name: "Section 23, Section 24",
    reason: "",
    reference: "https://www.foiman.com/archives/1712",
    searchStrings: [
        "section 23",
        "s.23",
        "s 23",
        "s23",
        "section 24",
        "s.24",
        "s 24",
        "s24",
      ],
  },
  {
    name: "Section 26",
    reason: "as releasing it might prejudice the defence of the UK.",
    reference: "https://www.foiman.com/archives/1825",
    searchStrings: [
        "section 26",
        "s.26",
        "s 26",
        "s26",
      ],
  },
  {
    name: "Section 27",
    reason: "as releasing it might prejudice the relationship between the UK and another state.",
    reference: "https://www.foiman.com/archives/1852",
    searchStrings: [
        "section 27",
        "s.27",
        "s 27",
        "s27",
      ],
  },
  {
    name: "Section 30, Section 31",
    reason: "as releasing it might prejudice an ongoing criminal investigation.",
    reference: "https://www.foiman.com/archives/1855",
    searchStrings: [
        "section 30",
        "s.30",
        "s 30",
        "s30",
        "section 31",
        "s.31",
        "s 31",
        "s31",
      ],
  },
  {
    name: "Section 35",
    reason: "as it relates to the formulation or development of goverment policy.",
    reference: "https://www.foiman.com/archives/1688",
    searchStrings: [
        "section 35",
        "s.35",
        "s 35",
        "s35",
      ],
  },
  {
    name: "Section 36",
    reason: "as it would prejudice the effective conduct of public affairs.",
    reference: "https://www.foiman.com/archives/861",
    searchStrings: [
        "section 36",
        "s.36",
        "s 36",
        "s36",
      ],
  },
  {
    name: "Section 40",
    reason: "because release of this data could impact someone's right to privacy.",
    reference: "https://www.foiman.com/archives/1143",
    searchStrings: [
        "section 40",
        "s.40",
        "s 40",
        "s40",
      ],
  },
  {
    name: "Section 41",
    reason: "because the information was provided to the authority by a third party in confidence.",
    reference: "https://www.foiman.com/archives/872",
    searchStrings: [
        "section 41",
        "s.41",
        "s 41",
        "s41",
      ],
  },
  {
    name: "Section 42",
    reason: "because this information is legal advice and subject to legal professional privilege.",
    reference: "https://www.foiman.com/archives/1143",
    searchStrings: [
        "section 42",
        "s.42",
        "s 42",
        "s42",
      ],
  },
  {
    name: "Section 43",
    reason: "because releasing this information would prejudice someone's commercial interest.",
    reference: "https://www.foiman.com/archives/1207",
    searchStrings: [
        "section 43",
        "s.43",
        "s 43",
        "s43",
      ],
  }
];
